apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  labels:
    app: customer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
      - name: customer-service
        image: ngquanghuyit/customer_sv:v1.0.1
        env:
        - name: MYSQL_URL
          value: mysql://nqhuy:123456@ecom_mysql_db:3306/customer_db
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  labels:
    app: customer-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: customer-service
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: customer-service-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: customer-service.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: customer-service
                port:
                  number: 8000